;; Draw a tree illustrating hte process generated by the count-change
;; procedure of section 1.1.2 in making change for 11 cents. What are
;; the orders of growth in the space and number of steps used by this
;; process as the amount to be changed increases?

(count-change amount) ->
(cc amount 5) -> (cc 11 5)
(cc amount kinds-of-coins
(cc 11 5) ->
  (cc 11 4) + 0 ->
   (cc 11 3) + 1 ->
    (cc 11 2) ->
      (cc 6 2) -> 
       (cc 1 2) -> + +
        1

;; The runtime evaluates to O(n^2), I think?